name: Release

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
            targets: aarch64-apple-darwin, x86_64-apple-darwin, x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu
      - name: Build
        run: cargo build --release \
            --target x86_64-unknown-linux-gnu \
            --target x86_64-pc-windows-gnu \
            --target aarch64-apple-darwin \
            --target x86_64-apple-darwin
      - uses: actions/upload-artifact@v4
        with:
            path: target/release/*/limelightctl