name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-build-linux-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y gcc-mingw-w64
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
            targets: aarch64-apple-darwin, x86_64-apple-darwin, x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
          --target x86_64-unknown-linux-gnu
          --target x86_64-pc-windows-gnu
      - name: Compress outputs
        run: |
          zstd -z target/x86_64-pc-windows-gnu/release/limelightctl.exe -o limelightctl-x86_64-pc-windows-gnu.exe.zst
          zstd -z target/x86_64-unknown-linux-gnu/release/limelightctl -o limelightctl-x86_64-unknown-linux-gnu.zst
      - uses: actions/upload-artifact@v4
        with:
          name: linux+windows
          path: 'limelightctl-*'
  
  release-build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
            targets: aarch64-apple-darwin
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release
          --target aarch64-apple-darwin
      - name: Compress outputs
        run: |
          zstd -z target/aarch64-apple-darwin/release/limelightctl -o limelightctl-aarch64-apple-darwin.zst
      - uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: 'limelightctl-*'

  release:
    runs-on: ubuntu-latest
    needs: [release-build-linux-windows, release-build-macos]
    steps:
      - uses: softprops/action-gh-release@v2
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        name: Create release
        with:
          files: '*/limelightctl-*'